# Generated by Django 3.2.4 on 2021-06-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uplod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('action', models.CharField(blank=True, choices=[('NO_FILTER', 'NO_FILTER'), ('HISTOGRAM', 'HISTOGRAM'), ('COLORIZE', 'COLORIZE'), ('GRAYSCALE', 'GRAYSCALE'), ('HSV', 'HSV CONVERGEN'), ('BLURRED', 'BLURRED'), ('BINARY', 'BINARY'), ('INVERT', 'BINARY INVERS'), ('EADGES', 'EADGES DETECTION'), ('NOICE', 'REDUCE NOICE')], max_length=50)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
